--1) STUDENT 테이블을 참조하여 ST_TEMP 테이블을 만들고 모든 학생의 성적을 4.5만점 기준으로 수정하세요
CREATE TABLE ST_TEMP
	AS SELECT * FROM STUDENT;

UPDATE ST_TEMP
	SET
		AVR = (AVR / 4.0) * 4.5;

SELECT *
	FROM ST_TEMP;

--2) PROFESSOR 테이블을 참조하여 PF_TEMP 테이블을 만들고 모든 교수의 부임일자를 100일 앞으로 수정하세요
CREATE TABLE PF_TEMP
	AS SELECT * FROM PROFESSOR;

UPDATE PF_TEMP
	SET
		 HIREDATE = HIREDATE + 100;

SELECT *
	FROM PF_TEMP;

--3) ST_TEMP 테이블에서 화학과 2학년 학생의 정보를 삭제하세요
DELETE FROM ST_TEMP
	WHERE MAJOR = '화학'
	  AND SYEAR = '2';

SELECT *
	FROM ST_TEMP;

--4) PF_TEMP 테이블에서 조교수의 정보를 삭제하세요
DELETE FROM PF_TEMP
	WHERE PNO IN (
				SELECT PNO
					FROM PROFESSOR
					WHERE ORDERS = '조교수'
	);
COMMIT;

SELECT *
	FROM PF_TEMP;

--5) EMP 테이블을 참조하여 EMP2 테이블을 만들고 
-- DNO = 30인 사원의 보너스를 15프로 상승시킨 값으로 변경하시고
-- DNO = 10인 사원의 보너스를 5프로 상승시킨 값으로 변경, 
-- DNO = 20인 사원의 급여를 10프로 상승시킨 값으로 변경하세요.
CREATE TABLE EMP2(
	ENO VARCHAR2(4),
	ENAME VARCHAR2(20),
	JOB VARCHAR2(10),
	MGR VARCHAR2(4),
	HDATE DATE,
	SAL NUMBER(5, 0),
	COMM NUMBER(5, 0),
	DNO VARCHAR2(2)
);

INSERT INTO EMP2
SELECT *
	FROM EMP;
COMMIT;

UPDATE EMP2
	SET 
		SAL = SAL * 1.15
	WHERE DNO = '30';
COMMIT;

UPDATE EMP2
	SET 
		SAL = SAL * 1.05
	WHERE DNO = '10';
COMMIT;

UPDATE EMP2
	SET 
		SAL = SAL * 1.1
	WHERE DNO = '20';
COMMIT;

--6) 화학과 2학년 학생중 기말고사 성적의 등급이 A, B인 정보를 갖는 테이블 SCORE_STGR을 생성하세요.(SNO, SNAME, MAJOR, SYEAR, RESULT, GRADE)

CREATE TABLE SCORE_STGR(
	SNO VARCHAR2(8),
	SNAME VARCHAR2(20),
	MAJOR VARCHAR2(20),
	SYEAR NUMBER(1, 0),
	RESULT NUMBER(3, 0),
	GRADE VARCHAR2(1)
);

INSERT INTO SCORE_STGR
SELECT ST.SNO 
	, ST.SNAME
	, ST.MAJOR 
	, ST.SYEAR 
	, SC.RESULT
	, SG.GRADE 
	FROM STUDENT ST
	JOIN SCORE SC
	  ON ST.SNO = SC.SNO 
	JOIN SCGRADE SG
	  ON SC.RESULT <= SG.HISCORE 
	  AND SC.RESULT >= SG.LOSCORE 
	WHERE SG.GRADE IN ('A', 'B');
COMMIT;

SELECT *
	FROM SCORE_STGR
	ORDER BY SNO;

--7) 생물학과 학생중 평점이 2.7이상인 학생이 수강중인 과목의 정보를 갖는 테이블 ST_COURSEPF를 생성하세요. (SNO, SNAME, CNO, CNAME, PNO, PNAME, AVR)
	  
CREATE TABLE ST_COURSEPF(
	SNO VARCHAR2(8),
	SNAME VARCHAR2(20),
	CNO VARCHAR2(8),
	CNAME VARCHAR2(20),
	PNO VARCHAR2(8),
	PNAME VARCHAR2(20),
	AVR NUMBER(4, 2)
);

INSERT INTO ST_COURSEPF
SELECT ST.SNO
	, ST.SNAME 
	, C.CNO
	, C.CNAME
	, P.PNO
	, P.PNAME
	, ST.AVR
	FROM STUDENT ST
	JOIN SCORE SC
	  ON SC.SNO = ST.SNO 
	JOIN COURSE C
	  ON C.CNO = SC.CNO 
	JOIN PROFESSOR P
	  ON P.PNO = C.PNO 
	WHERE ST.AVR >= 2.7
	  AND ST.MAJOR = '생물';
COMMIT;

SELECT *
	FROM ST_COURSEPF;
	  